mysite/accounts/urls.py
from django.urls import re_path as url
from . import views
# from django.contrib.auth.views import (password_reset, password_reset_done, password_reset_confirm)
from django.contrib.auth.views import PasswordResetView
# from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'accounts'
urlpatterns = [
    url(r'logout/$', LogoutView.as_view (template_name='accounts/logout.html'), name='logout'),
    url(r'^register/$', views.register, name = 'register'),
    url(r'^profile/$', views.view_profile, name= 'view_profile'),
    url(r'^profile/edit/$', views.edit_profile, name= 'edit_profile'),
    url(r'^profile/cancelled/$', views.cancel_subscription, name= 'cancel_subscription'),
    url(r'^change-password/$', views.change_password, name= 'change_password'),
    url(r'^profile/password/$', views.change_password, name= 'change_password'),
    url(r'^reset-password/$', PasswordResetView.as_view(), name='reset_password'),
    # url(r'^reset-password/done/$', password_reset_done.as_view(), name='password_reset_done'),
    # url(r'^reset-password/confirm/$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^profile/update_card/$', views.update_card, name='update_card'),
    # url(r'', login, {'template_name': 'accounts/login.html'}, name='login'),
    url(r'', LoginView.as_view(template_name='accounts/login.html'), name='login'),

]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
# import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    # path(r'__debug__', include(debug_toolbar.urls))
]

mysite/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)
    email = models.EmailField(default='')
    bt_id = models.CharField(max_length=50, default='0')
    subscription_id = models.CharField(max_length=50, default='0')
    status = models.CharField(max_length=50, default='0')




def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user = kwargs['instance'])


post_save.connect(create_profile, sender=User)

mysite/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
    #email = forms.EmailField(required = True)

    class Meta:
        model = User
        fields = (
        'username'
        ,'email'
        ,)

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            print(user.email)
            user.save()

        return user

class EditProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = (
            'email'
            ,'first_name'
            ,'last_name'
            ,'password')
        exclude = ()

mysite/accounts/views.py
from django.shortcuts import render, redirect
from accounts.forms import RegistrationForm, EditProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.conf import settings
import braintree
import sys, os
import uuid
# import stripe

gateway = braintree.BraintreeGateway(
    braintree.Configuration(
        environment=settings.BT_ENVIRONMENT,
        merchant_id=settings.BT_MERCHANT_ID,
        public_key=settings.BT_PUBLIC_KEY,
        private_key=settings.BT_PRIVATE_KEY,
    )
)
plan_id = settings.PLAN_ID

def generate_client_token():
    return gateway.client_token.generate()

def transact(options):
    return gateway.transaction.sale(options)

def find_transaction(id):
    return gateway.transaction.find(id)


from django.contrib import messages
from django.views.generic.edit import FormView

from django.template.loader import render_to_string

def register(request):

    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            customer = gateway.customer.create({
                "email": request.POST['email']
            })
            payment_token = gateway.payment_method.create({
                "customer_id":customer.customer.id,
                "payment_method_nonce": request.POST['payment_method_nonce']
            })
            token = payment_token.payment_method.token
            result = gateway.subscription.create({
                "payment_method_token": token,
                "plan_id": plan_id
            })
            if result.is_success or result.transaction:
                #sign in user
                user = form.save()
                u = User.objects.get(username = user.username)
                u.userprofile.bt_id = token
                u.userprofile.subscription_id = result.subscription.id
                u.userprofile.save()
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                args = {'subscription_status': str(check_status(request)), 'user':u}
                return render(request, 'accounts/profile.html', args)
            else:
                client_token = generate_client_token()
                error = '<ul class="errorlist"><li>Payment Method Declined</li></ul>'
                form = RegistrationForm(request.POST)
                args = {'form': form, 'client_token': client_token, 'error': error}
                return render(request, 'accounts/reg_form.html', args)

        else:
            client_token = generate_client_token()
            error = '<ul class="errorlist"><li>Username is already taken.</li></ul>'
            form = RegistrationForm(request.POST)
            args = {'form': form, 'client_token': client_token, 'error': error }
            return render(request, 'accounts/reg_form.html', args)
    else:
        client_token = generate_client_token()
        form = RegistrationForm(request.POST)
        args = {'form': form, 'client_token': client_token }#
        return render(request, 'accounts/reg_form.html', args)

# @login_required
def view_profile(request):
    args = {'user': request.user, 'subscription_status': check_status(request)}
    return render(request, 'accounts/profile.html', args)

# @login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user )

        if form.is_valid():
            form.save()
            return redirect('/accounts/profile')
        else:
            form = EditProfileForm(instance=request.user)
            args = {'form': form}
            return render(request, 'accounts/edit_profile.html', args )
    else:
        form = EditProfileForm(instance=request.user)
        args = {'form': form, 'user':request.user}
        return render(request, 'accounts/edit_profile.html', args )

def cancel_subscription(request):

    instance = request.user

    #TODO: need to add try catch block
    token = instance.userprofile.bt_id
    result = gateway.payment_method.delete(token)
    u = User.objects.get(username = instance.username)
    customer = u.username
    #instead of deleting the user change the username
    #TODO: Add active boolean field.
    u.username = u.username + str(uuid.uuid1)

    u.save()
    logout(request)
    args = {
    'user':customer
    }
    return render(request, 'accounts/cancelled.html', args )

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user )

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('/accounts/profile')
        else:
            return redirect('/account/change-password')
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form': form}
        return render(request, 'accounts/change_password.html', args )

def update_card(request):
    if request.method == 'POST':
        try:
            instance = request.user
            customer_id = instance.userprofile.bt_id
            payment_token = gateway.payment_method.update(customer_id,{
                "payment_method_nonce": request.POST['payment_method_nonce']
            })
            args = {'message':"Card updated successfully. Thank you."}
            return render(request, 'accounts/result.html', args )
        except :
            args = {'message':"Sorry something went wrong please try again later or contact us for help."}
            return render(request, 'accounts/result.html', args )

    else:
        client_token = generate_client_token()
        form = RegistrationForm(request.POST)
        args = {'form': form, 'client_token': client_token }#
        return render(request, 'accounts/update.html', args)

def check_status(request):
    username = request.user.username
    user = User.objects.get(username = username)
    subscription = gateway.subscription.find(user.userprofile.subscription_id)
    return subscription.status

mysite/accounts/templates/accounts/cancelled.html
<title>Profile</title>



<h4>Account cancelled</h4>
<div class="container">
  {{user}}

</div>

mysite/accounts/templates/accounts/change_password.html
{% block head %}
<title>Profile</title>
{% endblock %}
{% block body %}
<div class="container">
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" >Submit</button>

</form>

{% endblock %}

mysite/accounts/templates/accounts/edit_profile.html
<title>Profile</title>

{{error}}

<div>
<form method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" >Submit</button>
  
</form>
<a href="{% url 'accounts:cancel_subscription' %}">Cancell Subscription</a>
<br>
<a href="{% url 'accounts:update_card' %}">Update Card</a>
</div>

mysite/accounts/templates/accounts/login.html
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<title>BEST LOGIN IN PAGE IN THE WORLD</title>

<body>
<div class="container">

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Login</button>
    <a class="btn btn-primary" href="{% url 'accounts:register' %}">Register</a>
    <div class="form-group text-xs-center">
      <small><a href="{% url 'accounts:reset_password' %}">Forgot password?</a></small>
    </div>
  </form>
</div>



</body>

</html>

mysite/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h1>Logged Out!</h1>
    <p>
        Comeback soon!
    </p>

</div>
{% endblock %}

mysite/accounts/templates/accounts/profile.html
<title>Profile</title>
Subscription Status:
{{ subscription_status }}
<div class="container">
  <p>
  User Name: {{ user }}<br>
  First Name: {{user.first_name}}<br>
  Last Name: {{user.last_name}}<br>

  Email: {{user.email}}
  <br>
  <a href="{% url 'accounts:edit_profile' %}">Edit Profile</a>

</p>
</div>

mysite/accounts/templates/accounts/reg.html
{% extends 'base.html' %}

{% block body %}


<h3>{{user}}</h3>

<h3>{{email}}</h3>

{% endblock %}

mysite/accounts/templates/accounts/reg_form.html
<div class="container-fluid">
  <section class="container">
    <div class="container-page">
      <div class="row">
        <div class="col-md-6">
          <form id="payment-form" method="post" action=".">
            {{ error | safe }}
            <h3 class="dark-grey">Registration</h3>
            {% csrf_token %}

            <div class="form-group col-lg-6">
              <label>Username</label>

              {{ form.username }}

            </div>
            <br>
            <div class="form-group col-lg-6">
              <label>Password</label>
              {{ form.errorlist }}
              {{ form.password1 }}
            </div>
            <br>
            <div class="form-group col-lg-6">
              <label>Repeat Password</label>
              {{ form.password2 }}
              <p class="errorlist"><b id="validate-status"></b></p>
            </div>
            <div class="form-group col-lg-6">
              <label>Email</label>
              {{ form.errorlist }}
              {{ form.email }}
            </div>

            <div class="container"> By proceeding you agree to the terms and conditions

              <div class="form-group col-lg-8">
                <section>

                  <div class="bt-drop-in-wrapper">
                    <div id="bt-dropin"></div>
                  </div>
                </section>

                <input type="hidden" id="nonce" name="payment_method_nonce" />

                <div class="bt-drop-in-wrapper">
                  <div id="bt-dropin">
                    <button class="button" type="submit" id="submit-button"><span> Submit Payment</span></button>

                  </div>
                </div>

              </div>
            </div>

          </form>
        </div>
        <div class="col-lg-6">

        </div>
      </div>
      <div class="col-md-6">

      </div>
    </div>
  </section>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
  $("#id_username").addClass("form-control");
  $("#id_password1").addClass("form-control");
  $("#id_password2").addClass("form-control");
  $(".errorlist").css("color", "red");

  $(document).ready(function () {
    $("#id_password2").keyup(validate);
  });

  function validate() {
    var password1 = $("#id_password1").val();
    var password2 = $("#id_password2").val();

    if (password1 == password2) {
      $("#validate-status")
        .text("Match")
        .css("color", "green");
    } else {
      $("#validate-status")
        .text("No Match")
        .css("color", "red");
    }
  }
</script>

<script src="https://js.braintreegateway.com/web/dropin/1.19.0/js/dropin.min.js"></script>
<script>
  var form = document.querySelector('#payment-form');
  var client_token = '{{ client_token }}';

  braintree.dropin.create({
    authorization: client_token,
    container: '#bt-dropin',
    paypal: {
      flow: 'vault'
    }
  }, function (createErr, instance) {
    form.addEventListener('submit', function (event) {
      event.preventDefault();

      instance.requestPaymentMethod(function (err, payload) {
        if (err) {
          console.log('Error', err);
          return;
        }

        // Add the nonce to the form and submit
        document.querySelector('#nonce').value = payload.nonce;
        form.submit();
      });
    });
  });
</script>

mysite/accounts/templates/accounts/result.html
{% extends 'base.html' %} {% load static %} {% block body %}


<div class="container-fluid">
  <section class="container">
    <div class="container-page">
      <div class="row">
        <div class="col-md-6">
            {% csrf_token %}

          {{message}}
         </div>
        
      </div>
      <div class="col-md-6">

      </div>
    </div>
  </section>
</div>
{% endblock %}

mysite/accounts/templates/accounts/stuff.html
{% extends 'base.html' %}

{% block body %}


<h3>{{user}}</h3>


{% for i in stuff %}
<li>{{i}}</li>
{% endfor %}


{% endblock %}

mysite/accounts/templates/accounts/update.html
{% extends 'base.html' %} {% load static %} {% block body %}


<div class="container-fluid">
  <section class="container">
    <div class="container-page">
      <div class="row">
        <div class="col-md-6">
          <form id="payment-form" method="post" action=".">
            {{ error | safe }}
            {% csrf_token %}


            <div class="container"> 
              <div class="form-group col-lg-8">
                <section>
                  <label for="amount">
                    <div class="input-wrapper amount-wrapper">
                    </div>
                  </label>

                  <div class="bt-drop-in-wrapper">
                    <div id="bt-dropin"></div>
                  </div>
                </section>

                <input type="hidden" id="nonce" name="payment_method_nonce" />

                <div class="bt-drop-in-wrapper">
                  <div id="bt-dropin">
                    <button class="button" type="submit" id="submit-button"><span> Update Payment</span></button>

                  </div>
                </div>

              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </section>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script type="text/javascript">
  $("#id_username").addClass("form-control");
  $("#id_password1").addClass("form-control");
  $("#id_password2").addClass("form-control");
  $(".errorlist").css("color", "red");

  $(document).ready(function () {
    $("#id_password2").keyup(validate);
  });

  function validate() {
    var password1 = $("#id_password1").val();
    var password2 = $("#id_password2").val();

    if (password1 == password2) {
      $("#validate-status")
        .text("Match")
        .css("color", "green");
    } else {
      $("#validate-status")
        .text("No Match")
        .css("color", "red");
    }
  }
</script>

<script src="https://js.braintreegateway.com/web/dropin/1.19.0/js/dropin.min.js"></script>
<script>
  var form = document.querySelector('#payment-form');
  var client_token = '{{ client_token }}';

  braintree.dropin.create({
    authorization: client_token,
    container: '#bt-dropin',
    paypal: {
      flow: 'vault'
    }
  }, function (createErr, instance) {
    form.addEventListener('submit', function (event) {
      event.preventDefault();

      instance.requestPaymentMethod(function (err, payload) {
        if (err) {
          console.log('Error', err);
          return;
        }

        // Add the nonce to the form and submit
        document.querySelector('#nonce').value = payload.nonce;
        form.submit();
      });
    });
  });
</script>
{% endblock %}